### ISSUE TITLE
AWS ACCESS KEY, SECRET 등록 시 unauthorized 떠요. 

### ISSUE THREAD

**Issue by qkrwjdan** [Fightim/client-gui#19]
<img width="1511" alt="스크린샷 2022-11-28 오후 5 03 40" src="https://user-images.githubusercontent.com/44994031/204225021-2ebf00cc-27ff-40c4-91be-ac465a70689e.png">

**Comment by joohaem** [comment]
https://github.com/Fightim/client-gui/pull/28
